Cache 404 errors (#295)
**Motivation**
This PR tries to avoid the following scenario:

```
debug: [Cache] Cache miss: 5_0x710085cB90e4Ce09F80E354Cf579a32C9790A140_contract
debug: [Cache] Cache miss: 5_0x710085cB90e4Ce09F80E354Cf579a32C9790A140_contract
debug: [Cache] Cache miss: 5_0x40A2aCCbd92BCA938b02010E17A5b8929b49130D_contract
debug: [Cache] Cache miss: 5_0xf10E2042ec19747401E5EA174EfB63A0058265E6_contract
debug: [Cache] Cache miss: 5_0x7f3774E7D0e410444b6f19a10D50Cd34857Bb236_contract
debug: [Cache] Cache miss: 5_0x7f3774E7D0e410444b6f19a10D50Cd34857Bb236_contract
debug: [Cache] Cache miss: 5_0x7f3774E7D0e410444b6f19a10D50Cd34857Bb236_contract
...
error: An error occurred {"code":404}
error: An error occurred {"code":404}
error: An error occurred {"code":404}
error: An error occurred {"code":404}
error: An error occurred {"code":404}
error: An error occurred {"code":404}
error: An error occurred {"code":404}
...
```

i.e: Avoid making successive calls to the Transaction Service asking for
the same item.

This is common in the current flow since a list of transactions could
contain references to the same contract for each transaction. The
current behavior is to repeat the call to the Transaction Service N
times for N contracts, whether the contract is found or it doesn't.

So this PR:
- Modifies the `get` function of the `CacheFirstDataSource` class to
cache 404 errors. The errors are cached with a fixed TTL of 30 seconds
in this first approach. Optionally in the future, we could want to
externalize this configuration and place this TTL value behind an
environment variable.